site_name: GamesVessel API Document

######################structure#####################
nav:
  - Home: index.md

  - Get Started: get_started.md

  - Server Java:
    - OLAP:
      - Cube管理: server_java/olap/olap1.md
      - 核心查询: server_java/olap/olap2.md
      - Change Log: server_java/olap/change_log.md
    - Dictionary: server_java/dictionary/dictionary.md

  - Server Python: 
    - Demo: server_python/demo/demo.md

######################configurations#####################
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    # - toc.integrate
    - search.highlight

plugins:
  - search:
      lang: en

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.tabbed
